// Turns ../catalog.json into migrations/0002_seed_exercises.sql. The output is
// committed; rerun this after editing the catalog and commit the diff.
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const here = fileURLToPath(new URL(".", import.meta.url));
const catalogPath = new URL("../../catalog.json", import.meta.url);
const outPath = new URL("../migrations/0002_seed_exercises.sql", import.meta.url);

const PATTERNS = new Set(["push", "squat", "hinge", "core", "cardio", "mobility"]);
const UNITS = new Set(["reps", "seconds"]);

const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;
const bit = (value) => (value ? 1 : 0);

const catalog = JSON.parse(await readFile(catalogPath, "utf8"));
if (!Array.isArray(catalog) || catalog.length === 0) throw new Error("catalog.json is empty");

const seen = new Set();
const rows = catalog.map((exercise, index) => {
  const where = `catalog.json[${index}] (${exercise.id})`;
  for (const key of ["id", "name", "pattern", "unit", "cue"]) {
    if (typeof exercise[key] !== "string" || exercise[key].length === 0) {
      throw new Error(`${where}: ${key} must be a non-empty string`);
    }
  }
  if (seen.has(exercise.id)) throw new Error(`${where}: duplicate id`);
  seen.add(exercise.id);
  if (!PATTERNS.has(exercise.pattern)) throw new Error(`${where}: bad pattern`);
  if (!UNITS.has(exercise.unit)) throw new Error(`${where}: bad unit`);
  for (const key of ["easy", "medium", "hard"]) {
    const n = exercise[key];
    if (!Number.isInteger(n) || n < 1 || n > 1000) throw new Error(`${where}: ${key} must be 1..1000`);
  }
  for (const key of ["office_ok", "needs_floor", "intense"]) {
    if (typeof exercise[key] !== "boolean") throw new Error(`${where}: ${key} must be a boolean`);
  }
  return `  (${[
    quote(exercise.id),
    quote(exercise.name),
    quote(exercise.pattern),
    quote(exercise.unit),
    exercise.easy,
    exercise.medium,
    exercise.hard,
    quote(exercise.cue),
    bit(exercise.office_ok),
    bit(exercise.needs_floor),
    bit(exercise.intense),
    index,
  ].join(", ")})`;
});

const ids = catalog.map((exercise) => quote(exercise.id)).join(", ");
const sql = `-- Generated by scripts/gen-seed.mjs from catalog.json. Do not edit by hand.
-- ${catalog.length} exercises.
INSERT OR REPLACE INTO exercises
  (id, name, pattern, unit, easy, medium, hard, cue, office_ok, needs_floor, intense, sort_order)
VALUES
${rows.join(",\n")};

-- Drops anything the catalog no longer lists, so rerunning this file is a
-- complete sync rather than an append.
DELETE FROM exercises WHERE id NOT IN (${ids});
`;

await writeFile(outPath, sql);
console.log(`wrote ${fileURLToPath(outPath).replace(here, "")} (${catalog.length} exercises)`);
