-- Generated by scripts/gen-seed.mjs from catalog.json. Do not edit by hand.
-- 30 exercises.
INSERT OR REPLACE INTO exercises
  (id, name, pattern, unit, easy, medium, hard, cue, office_ok, needs_floor, intense, sort_order)
VALUES
  ('wall_pushup', 'Wall push-up', 'push', 'reps', 10, 18, 28, 'Body straight, elbows back at 45 degrees, chest to wall', 1, 0, 0, 0),
  ('incline_pushup', 'Incline push-up on desk', 'push', 'reps', 8, 14, 22, 'Hands on desk edge, ribs down, chest touches, full lockout', 1, 0, 0, 1),
  ('knee_pushup', 'Knee push-up', 'push', 'reps', 6, 12, 20, 'Knees, hips, shoulders in one line; chest leads down', 0, 1, 0, 2),
  ('full_pushup', 'Push-up', 'push', 'reps', 5, 10, 18, 'Squeeze glutes, elbows tucked 45 degrees, lock out every rep', 0, 1, 0, 3),
  ('decline_pushup', 'Feet-elevated push-up', 'push', 'reps', 4, 8, 14, 'Feet on chair, hips level, lower chest between hands', 0, 1, 0, 4),
  ('chair_dip', 'Chair dip', 'push', 'reps', 6, 12, 20, 'Hands on seat edge, elbows straight back, shoulders down', 1, 0, 0, 5),
  ('sit_to_stand', 'Sit-to-stand', 'squat', 'reps', 10, 16, 24, 'Stand without hands, then lower slowly to the seat', 1, 0, 0, 6),
  ('air_squat', 'Air squat', 'squat', 'reps', 10, 18, 28, 'Sit hips back, knees track toes, stand tall', 1, 0, 0, 7),
  ('squat_hold', 'Squat hold', 'squat', 'seconds', 20, 35, 60, 'Chest up, weight in midfoot, breathe, do not hold breath', 1, 0, 0, 8),
  ('wall_sit', 'Wall sit', 'squat', 'seconds', 20, 40, 60, 'Back flat on wall, thighs parallel, knees above ankles', 1, 0, 0, 9),
  ('reverse_lunge', 'Reverse lunge (per side)', 'squat', 'reps', 6, 10, 14, 'Step back, drop rear knee, drive through front heel', 1, 0, 0, 10),
  ('calf_raise', 'Standing calf raise', 'squat', 'reps', 15, 25, 40, 'Rise onto toes, pause one second, lower under control', 1, 0, 0, 11),
  ('standing_good_morning', 'Standing good morning', 'hinge', 'reps', 10, 15, 22, 'Hands on hips, push hips back, keep back flat', 1, 0, 0, 12),
  ('single_leg_rdl', 'Single-leg deadlift (per side)', 'hinge', 'reps', 6, 9, 12, 'Hinge over standing leg, hips square, back leg straight', 1, 0, 0, 13),
  ('glute_bridge', 'Glute bridge', 'hinge', 'reps', 12, 20, 30, 'Ribs down, squeeze glutes at top, avoid arching low back', 0, 1, 0, 14),
  ('superman', 'Superman', 'hinge', 'reps', 8, 14, 20, 'Lift chest and thighs, look down, pause one second', 0, 1, 0, 15),
  ('forearm_plank', 'Forearm plank', 'core', 'seconds', 20, 40, 60, 'Elbows under shoulders, squeeze glutes, ribs down, keep breathing', 0, 1, 0, 16),
  ('side_plank', 'Side plank (per side)', 'core', 'seconds', 15, 25, 40, 'Elbow under shoulder, hips stacked and lifted, neck neutral', 0, 1, 0, 17),
  ('dead_bug', 'Dead bug (per side)', 'core', 'reps', 6, 10, 14, 'Press low back flat, extend opposite arm and leg', 0, 1, 0, 18),
  ('bird_dog', 'Bird dog (per side)', 'core', 'reps', 6, 10, 14, 'Reach opposite arm and leg, keep hips square, pause', 0, 1, 0, 19),
  ('standing_knee_to_elbow', 'Standing knee to opposite elbow', 'core', 'reps', 10, 16, 24, 'Stand tall, draw knee to opposite elbow, exhale hard', 1, 0, 0, 20),
  ('march_in_place', 'March in place', 'cardio', 'seconds', 45, 60, 90, 'Tall posture, knees to hip height, swing the arms', 1, 0, 0, 21),
  ('step_jacks', 'Step jacks', 'cardio', 'reps', 20, 35, 50, 'Step side to side, arms sweep overhead, no jumping', 1, 0, 1, 22),
  ('jumping_jacks', 'Jumping jacks', 'cardio', 'reps', 20, 35, 50, 'Land soft on the forefoot, full overhead arm sweep', 0, 0, 1, 23),
  ('high_knees', 'High knees', 'cardio', 'seconds', 20, 30, 45, 'Quick light steps, knees to hip height, arms driving', 0, 0, 1, 24),
  ('stair_climb', 'Stair climb', 'cardio', 'seconds', 30, 45, 60, 'Steady quick pace, whole foot on step, use rail', 1, 0, 1, 25),
  ('doorway_chest_stretch', 'Doorway chest stretch (per side)', 'mobility', 'seconds', 20, 30, 45, 'Forearm on frame, elbow shoulder height, step through gently', 1, 0, 0, 26),
  ('seated_thoracic_rotation', 'Seated thoracic rotation (per side)', 'mobility', 'reps', 6, 8, 10, 'Hands behind head, rotate rib cage, keep hips still', 1, 0, 0, 27),
  ('calf_stretch_wall', 'Wall calf stretch (per side)', 'mobility', 'seconds', 20, 30, 45, 'Back leg straight, heel down, hips forward toward wall', 1, 0, 0, 28),
  ('half_kneeling_hip_flexor', 'Half-kneeling hip flexor stretch (per side)', 'mobility', 'seconds', 20, 30, 45, 'Tuck tailbone, squeeze rear glute, stay tall, do not lean', 0, 1, 0, 29);

-- Drops anything the catalog no longer lists, so rerunning this file is a
-- complete sync rather than an append.
DELETE FROM exercises WHERE id NOT IN ('wall_pushup', 'incline_pushup', 'knee_pushup', 'full_pushup', 'decline_pushup', 'chair_dip', 'sit_to_stand', 'air_squat', 'squat_hold', 'wall_sit', 'reverse_lunge', 'calf_raise', 'standing_good_morning', 'single_leg_rdl', 'glute_bridge', 'superman', 'forearm_plank', 'side_plank', 'dead_bug', 'bird_dog', 'standing_knee_to_elbow', 'march_in_place', 'step_jacks', 'jumping_jacks', 'high_knees', 'stair_climb', 'doorway_chest_stretch', 'seated_thoracic_rotation', 'calf_stretch_wall', 'half_kneeling_hip_flexor');
